name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository }}
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Amalgamate headers
      run: python amalgamate.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ github.sha }}
        path: out/

    - uses: TheMrMilchmann/setup-msvc-dev@fb19abb8a41b3cf0340f5d1be17d420309232be6 # v3.0.1
      with:
        arch: x64

    - name: Test (add_subdirectory)
      run: |
        cmake -B build -S test -G Ninja
        cmake --build build
        echo Running test-c.exe
        .\build\test-c.exe
        echo Running test-cpp.exe
        .\build\test-cpp.exe

    - name: Test (find_package)
      run: |
        cmake -B build-pkg -S test -G Ninja -DPHNT_TEST_PACKAGE=ON
        cmake --build build-pkg
        echo Running test-c.exe
        .\build-pkg\test-c.exe
        echo Running test-cpp.exe
        .\build-pkg\test-cpp.exe

    - name: Compress artifacts
      uses: vimtor/action-zip@26a249fb00d43ca98dad77a4b3838025fc226aa1 # v1.1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        files: out/
        dest: phnt.zip

    - name: Release
      uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        files: |
          out/phnt.h
          phnt.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
